//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneAPI.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank
    {
        public int Id { get; set; }
        public Nullable<int> AccountId { get; set; }
        public string FullName { get; set; }
        public string CardNumber { get; set; }
        public string ExpiredDate { get; set; }
        public Nullable<int> CVV { get; set; }
        public string Brand { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
