//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneAPI.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDetail
    {
        public int Id { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string Screen { get; set; }
        public string OS { get; set; }
        public string FrontCamera { get; set; }
        public string BackCamera { get; set; }
        public string Chip { get; set; }
        public string RAM { get; set; }
        public string Memory { get; set; }
        public string SIM { get; set; }
        public string Battery { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
